opcache.enable=1
opcache.enable_cli=1

opcache.memory_consumption=512
opcache.interned_strings_buffer=64
opcache.max_accelerated_files=50000

# Revalidate file changes quickly so deleted/updated plugins take effect immediately
opcache.validate_timestamps=1
opcache.revalidate_freq=1

opcache.enable_file_override=1
opcache.save_comments=1